- name: Set in-toto up
  hosts: all
  gather_facts: true
  tasks:
    - name: Install python3
      win_chocolatey:
          name: python310
          state: present
    - name: Install git
      win_chocolatey:
          name: git
          state: present

    - name: Install tox
      win_command: "pip install tox"

    - name: Install in-toto
      win_shell: |
          git clone https://github.com/in-toto/in-toto 
          cd in-toto
          tox -e py310
